name = "IntermediateLean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["IntermediateLean"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
# rev = "v4.20.0-rc5"

[[lean_lib]]
name = "IntermediateLean"
